# Configuration script for use with continuous integration service appveyor.com
environment:
  matrix:
    - MINGW_ARCH: x86_64
      BINDIR: C:\msys64\mingw64
      BOOST_ROOT: C:\msys64\mingw64
      BOOST_LIBRARYDIR: C:\msys64\mingw64\lib
      BOOST_INCLUDEDIR: C:\msys64\mingw64\include\boost
      GENERATOR: MSYS Makefiles
      BUILD_TYPE: Release
      PYTHON_DIR: C:\Python36-x64
      CMAKE_ARGS: -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++
      CMAKE_EXTRA: -DPARALLEL=ON -DXCSF_PYLIB=ON

before_build:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  # Set MinGW and Python3 path
  - set "PATH=%PYTHON_DIR%;%PATH%;%BINDIR%;%BOOST_LIBRARYDIR%"
  - cd build
  - cmake --version
  - cmake -DCMAKE_BUILD_TYPE=%BUILD_TYPE% %CMAKE_ARGS% %CMAKE_EXTRA% -G "%GENERATOR%" ..

build_script: cmake --build . --config %CONFIGURATION%
