# Configuration script for use with continuous integration service appveyor.com
environment:
  matrix:
    - MINGW_ARCH: x86_64
      GENERATOR: MinGW Makefiles
      Compiler: MinGW64-gcc-7.2.0
      BINDIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
      BUILD_TYPE: Release
      PYTHON_DIR: C:\Python36-x64
      BOOST_ROOT: C:\Libraries\boost_1_69_0
      BOOST_LIBRARYDIR: C:\Libraries\boost_1_67_0\lib64-msvc-14.0
      CMAKE_ARGS: -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++
      CMAKE_EXTRA: -DPARALLEL=ON -DXCSF_PYLIB=ON -DBoost_USE_STATIC_LIBS=ON

before_build:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  # Set MinGW and Python3 path
  - set "PATH=%PYTHON_DIR%;%PATH%;%BINDIR%;%BOOST_LIBRARYDIR%"
  - cd build
  - cmake --version
  - cmake -DCMAKE_BUILD_TYPE=%BUILD_TYPE% %CMAKE_ARGS% %CMAKE_EXTRA% -G "%GENERATOR%" ..

build_script: cmake --build . --config %CONFIGURATION%
