# Configuration script for use with continuous integration service appveyor.com

environment:
  matrix:
    - compiler: gcc-6.3.0-posix
      BUILD_SYSTEM: cmake
      GENERATOR: "MinGW Makefiles"
      C_PATH: 'C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin'
      CXX_PATH: 'C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin'
      BOOST_ROOT: C:\Libraries\boost_1_69_0
      CMAKE_EXTRA_OPTIONS: -DPARALLEL=OFF

configuration:
  - Release

build_script:
  - cd build
  - cmake
    -G"%GENERATOR%"
    %CMAKE_ARGS%
    "-DCMAKE_BUILD_TYPE=%configuration%"
    %CMAKE_EXTRA_OPTIONS%
    ..
  - msbuild xcsf.sln
