# Configuration script for use with continuous integration service appveyor.com

version: 1.0.{build}

image: Visual Studio 2019

environment:
  BOOST_ROOT: C:\Libraries\boost_1_71_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_71_0\lib

build:
  parallel: true

build_script:
  - cd build
  - cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_C_COMPILER=clang-cl.exe -DCMAKE_CXX_COMPILER=clang-cl.exe -DBoost_USE_STATIC_LIBS="ON" -DBoost_USE_STATIC_RUNTIME="ON" ..
  - msbuild xcsf.sln
