# Configuration script for use with continuous integration service appveyor.com

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      COMPILER: mingw64
      TOOLSET: MinGW-w64
      ARCH: x86_64
      GENERATOR: MinGW Makefiles
      MINGW_DIR_BIN: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/
      CMAKE_C_COMPILER: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/gcc.exe
      CMAKE_CXX_COMPILER: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/g++.exe
      BOOST_ROOT: C:\Libraries\boost_1_69_0
      CMAKE_EXTRA_OPTIONS: -DPARALLEL=OFF

configuration:
  - Release

build_script:
  - cd build
  - cmake
    -G "%GENERATOR%"
    %CMAKE_ARGS%
    "-DCMAKE_BUILD_TYPE=%configuration%"
    %CMAKE_EXTRA_OPTIONS%
    ..
  - msbuild xcsf.sln
