# Configuration script for use with continuous integration service appveyor.com
environment:
  matrix:
    - COMPILER: MinGW-w64
      GENERATOR: MinGW Makefiles
      PLATFORM: x64
      BUILD_TYPE: Release
      BOOST_ROOT: C:\Libraries\boost_1_69_0
      CMAKE_ARGS: -DPARALLEL=OFF

before_build:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
  - set PATH=C:\MinGW\bin;%PATH%
  - cd build
  - cmake -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%BUILD_TYPE% %CMAKE_ARGS% ..

build_script: cmake --build . --config %CONFIGURATION%

build:
  verbosity: detailed
