# Configuration script for use with continuous integration service appveyor.com
environment:
  matrix:
    - GENERATOR: MinGW Makefiles
      BUILD_TYPE: Release
      BOOST_ROOT: C:\Libraries\boost_1_69_0
      CMAKE_ARGS: -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++
      CMAKE_EXTRA: -DPARALLEL=OFF

before_build:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
  - set PATH=C:\MinGW\bin;%PATH%
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=%BUILD_TYPE% %CMAKE_ARGS% %CMAKE_EXTRA% -G "%GENERATOR%" ..

build_script: cmake --build . --config %CONFIGURATION%
