# Configuration script for use with continuous integration service appveyor.com

version: 1.0.{build}

image: Visual Studio 2015

environment:
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib64-msvc-14.0

  matrix:
    - COMPILER: "clang"

build:
  parallel: true

build_script:
  - cd build
  - cmake -G "Visual Studio 14 2015" -DPARALLEL="OFF" ..
  - msbuild xcsf.sln
