# Configuration script for use with continuous integration service appveyor.com

version: 1.0.{build}

os:
  - Visual Studio 2017

environment:
  CLANG_URL: "https://releases.llvm.org/9.0.0/LLVM-9.0.0-win64.exe"
  BOOST_ROOT: C:\Libraries\boost_1_69_0

  matrix:
    - BUILD: -G "Visual Studio 15 2017" -A x64

build:
  verbosity: detailed

build_script:
  - appveyor DownloadFile %CLANG_URL% -FileName llvm-installer.exe
  - llvm-installer.exe /S /D=C:\LLVM
  - set PATH=C:\LLVM\bin;%PATH%
  - clang-cl -v
  - cd build
  - cmake %BUILD% -DCMAKE_C_COMPILER=clang-cl.exe -DCMAKE_CXX_COMPILER=clang-cl.exe -DPARALLEL="OFF" ..
  - msbuild xcsf.sln
