---
# Configuration script for use with continuous integration service lgtm.com
path_classifiers:
  docs:
    - doc
  test:
    - test
  library:
    - lib

extraction:
  cpp:
    index:
      build_command:
        - cd $LGTM_SRC/build
        - cmake -DCMAKE_BUILD_TYPE=Debug ..
        - make -j2
...
