---
# Configuration script for use with continuous integration service travis-ci.com

language: cpp

git:
  depth: false

dist: bionic

matrix:
  include:
    # Sonar build
    - os: linux
      compiler: gcc
      addons: &gcc6
        apt:
          packages: ['g++-6']
        sonarcloud:
          organization: "rpreen"
      env: BUILD_TYPE="Debug" XCSF_PYLIB="OFF" SONAR="ON"

    # Python library Ubuntu 18.04
    - os: linux
      compiler: gcc
      addons: &gcc6
        apt:
          packages: ['g++-6', 'python3']
      env: BUILD_TYPE="Release" XCSF_PYLIB="ON" ENABLE_TESTS="ON"

    # Python library OSX
    - os: osx
      osx_image: xcode10.1
      compiler: clang
      env: BUILD_TYPE="Release" XCSF_PYLIB="ON" ENABLE_TESTS="ON"

    # Doxygen
    - os: linux
      compiler: gcc
      addons: &gcc6
        apt:
          packages: ['doxygen', 'graphviz']
      env: DOXYGEN="ON" BUILD_TYPE="Release" XCSF_PYLIB="ON" ENABLE_TESTS="ON"
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_REPO_TOKEN
        on:
          branch: master

before_script:
  - |
    if [[ "${TRAVIS_OS_NAME}" != "linux" ]]; then
      brew unlink python@2
      brew install llvm
      brew install libomp
      brew install cmake || brew upgrade cmake
    fi

script:
  - cd "${TRAVIS_BUILD_DIR}/build"
  - cmake
    -DCMAKE_BUILD_TYPE="$BUILD_TYPE"
    -DXCSF_PYLIB="$XCSF_PYLIB"
    -DENABLE_TESTS="$ENABLE_TESTS"
    ..
  - |
    if [[ "${SONAR}" == "ON" ]]; then
      cp ../.sonar-project.properties ./sonar-project.properties;
      wget -q https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip;
      unzip -q build-wrapper-linux-x86.zip;
      cp ./build-wrapper-linux-x86/libinterceptor-x86_64.so \
      ./build-wrapper-linux-x86/libinterceptor-haswell.so;
      ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 \
      --out-dir bw-output make clean all;
      sonar-scanner;
    elif [[ "${DOXYGEN}" == "ON" ]]; then
      make doc -j2
    else
      make -j2
    fi
...
