language: cpp

dist: bionic

matrix:
  include:
    # Stand-alone Ubuntu 18.04
    - os: linux
      compiler: gcc
      addons: &gcc6
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env: BADGE=linux BUILD_TYPE="RELEASE" XCSF_PYLIB="OFF"

    # Python library Ubuntu 18.04
    - os: linux
      compiler: gcc
      addons: &gcc6
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'python3', 'libboost-python-dev', 'libboost-numpy-dev']
      env: BADGE=linux BUILD_TYPE="RELEASE" XCSF_PYLIB="ON"

    # Stand-alone OSX
    - os: osx
      osx_image: xcode10.1
      compiler: gcc
      env: BADGE=osx BUILD_TYPE="RELEASE" PARALLEL="ON" XCSF_PYLIB="OFF" 
 
    # Python library OSX
    - os: osx
      osx_image: xcode10.1
      compiler: gcc
      env: BADGE=osx BUILD_TYPE="RELEASE" PARALLEL="ON" XCSF_PYLIB="ON" 
 
script:
  - cd "${TRAVIS_BUILD_DIR}/build"
  - |
    if [[ "${TRAVIS_OS_NAME}" != "linux" ]]; then
      curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
      source ./macports-ci install
      sudo port install gcc9 libomp cmake
      if [[ "${XCSF_PYLIB}" == "ON" ]]; then
        sudo port install python37 python3-mt
      fi
      cmake -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9 -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DXCSF_PYLIB="$XCSF_PYLIB" ..
    else
      cmake -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DXCSF_PYLIB="$XCSF_PYLIB" ..
    fi
  - make
