---
# Configuration script for use with continuous integration service travis-ci.com

language: cpp

git:
  depth: false

dist: focal

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc9
        apt:
          packages: ['g++-9']
        sonarcloud:
          organization: "rpreen"
      env: BUILD_TYPE=Debug XCSF_PYLIB=OFF

script:
  - cd "${TRAVIS_BUILD_DIR}/build"
  - cmake
    -DCMAKE_BUILD_TYPE="$BUILD_TYPE"
    -DXCSF_PYLIB="$XCSF_PYLIB"
    -DENABLE_TESTS="$ENABLE_TESTS"
    ..
  - |
    cp ../.sonar-project.properties ./sonar-project.properties;
    wget -q https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip;
    unzip -q build-wrapper-linux-x86.zip;
    cp ./build-wrapper-linux-x86/libinterceptor-x86_64.so \
    ./build-wrapper-linux-x86/libinterceptor-haswell.so;
    ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 \
    --out-dir bw-output make clean all;
    sonar-scanner;
...
