language: cpp

dist: bionic # Ubuntu 18.04

matrix:
  include:
    # Stand-alone
    - os: linux
      compiler: gcc
      addons: &gcc6
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env: BADGE=linux BUILD_TYPE="RELEASE" XCSF_PYLIB="OFF"

    # Python library
    - os: linux
      compiler: gcc
      addons: &gcc6
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'python3', 'libboost-python-dev', 'libboost-numpy-dev']
      env: BADGE=linux BUILD_TYPE="RELEASE" XCSF_PYLIB="ON"

    # Stand-alone
    - os: osx
      compiler: gcc
      env: BADGE=osx BUILD_TYPE="RELEASE" PARALLEL="ON" XCSF_PYLIB="OFF" 

script:
  - cd "${TRAVIS_BUILD_DIR}/build"
  - |
    if [[ "${TRAVIS_OS_NAME}" != "linux" ]]; then
      softwareupdate --list
      softwareupdate --install "Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.4"
      brew install gcc libomp
      brew install cmake || brew upgrade cmake
      cmake -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9 -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DXCSF_PYTHON_LIBRARY="$XCSF_PYLIB" ..
    else
      cmake -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DXCSF_PYTHON_LIBRARY="$XCSF_PYLIB" ..
    fi
  - make
