---
# Configuration script for github continuous integration service

name: macOS build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Configure
        env:
          CC: gcc-11
          CXX: g++-11
        working-directory: build
        run: cmake ..
          -DCMAKE_BUILD_TYPE=Release
          -DXCSF_PYLIB=ON
          -DENABLE_TESTS=ON

      - name: Build
        working-directory: build
        run: cmake --build . --config Release -j2
...
