---
# Workflow to build wheels.

name: Wheel builder

on: workflow_dispatch

jobs:
  build_wheels:
    name: Build wheel for ${{ matrix.python }}-${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-11]

    steps:
      - name: Checkout xcsf
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Python3
        uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.15.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.platform }}
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_BUILD_VERBOSITY: 3

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
...
