---
# Configuration script for github continuous integration service

name: Windows build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure
        env:
          CC: gcc-9
          CXX: g++-9
        working-directory: build
        run: cmake ..
          -DCMAKE_BUILD_TYPE=Release
          -DXCSF_PYLIB=ON
          -DENABLE_TESTS=ON

      - name: Build
        working-directory: build
        run: cmake --build . --config $BUILD_TYPE -j2
...
